Opening a FB group Page
oss2019/naarad pull request #19
Opened 2019-05-27 22:07 UTC by iharshit009

2019-05-27 22:07 UTC, pep8speaks commented
Hello @iharshit009! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`open_group.py`](https://github.com/oss2019/naarad/blob/8e5c6f9337f009d0d97f12193e9470e6df682b45/open_group.py):

> [Line 35:1](https://github.com/oss2019/naarad/blob/8e5c6f9337f009d0d97f12193e9470e6df682b45/open_group.py#L35): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2019-05-27 22:15 UTC, iharshit009 commented
sir i am getting an issue of automatically closing of chrome window after the execution of code...
I have tried many attempts but could not work and the commented lines are by which the window can be stopped from being closed...but they also could not work....

2019-05-28 16:30 UTC, thealphadollar requested changes
Please create a separate method inside the Facebook class alongside the already existing login method; do not mix up both in the same method.

2019-05-29 16:50 UTC, iharshit009 commented
commited, please give reviews..

2019-05-29 19:40 UTC, thealphadollar commented on open_group.py
> +        self.group_page()
Please trigger this method from __init__.

2019-05-29 19:41 UTC, thealphadollar requested changes
Please do the following changes?

2019-05-29 19:41 UTC, thealphadollar commented on open_group.py
> +        self.driver.get(self.link)
instead of using self.link, please pass link as an argument to the function `group_page`.

Also, give it a better name like, "open_group".

2019-05-31 05:06 UTC, iharshit009 commented
@thealphadollar sir i have made the changes, but there is an issue of automatically closing the browser window , I am looking on it..

2019-06-02 08:36 UTC, thealphadollar approved these changes
Great work @iharshit009 ! 

Apologies for the late response.

2019-06-02 08:36 UTC, merged

2019-06-02 09:56 UTC, iharshit009 commented
No worries sir, But the problem of automatically closing the browser after execution is not solved..

2019-06-02 15:37 UTC, thealphadollar commented
We will implement more routing and hence that won't be an issue.

On Sun, Jun 2, 2019 at 3:26 PM HARSHIT JAIN <notifications@github.com>
wrote:

> No worries sir, But the problem of automatically closing the browser after
> execution is not solved..
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/oss2019/naarad/pull/19?email_source=notifications&email_token=AH2K2IDM3VSNH5LHIHMEFXLPYOKM3A5CNFSM4HP6SADKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWXSBRA#issuecomment-498016452>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AH2K2IBMC2W6ONTU3GWIMCLPYOKM3ANCNFSM4HP6SADA>
> .
>