file to get the details for the post into groups
oss2019/naarad pull request #21
Opened 2019-06-08 14:26 UTC by iharshit009

2019-06-08 14:26 UTC, pep8speaks commented
Hello @iharshit009! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`accept_data.py`](https://github.com/oss2019/naarad/blob/fe53f5dd8b121b37fa740d988afbb6088050cf92/accept_data.py):

> [Line 64:1](https://github.com/oss2019/naarad/blob/fe53f5dd8b121b37fa740d988afbb6088050cf92/accept_data.py#L64): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1

2019-06-08 14:45 UTC, thealphadollar requested changes
This is an amazing PR. Thanks a lot for it :sparkle: 

I would request you to keep all this in the folder `src` which has the __init__.py file and delete entries such as `fb_login.py`, `open_group.py` and others which we won't be using :)

Also segregate different input in different methods.

For e.g. accept username and password in one function, and details for post in another.

Again, this is a great PR and almost finishes the skeleton of the project.

2019-06-08 16:02 UTC, iharshit009 commented
Sir, please have a check at the PR

2019-06-08 22:57 UTC, thealphadollar requested changes
Fabulous work :) I'm highly thankful to you for this.

Please implement the last set of changes and then we shall move on with more.

Also, please rename the file `src/accept_data.py` to `app.py` or `main.py`

2019-06-08 22:57 UTC, thealphadollar commented on src/accept_data.py
> +        self.group = self.group.split(',')
self.groups would be a better name

2019-06-09 09:24 UTC, thealphadollar approved these changes
Thanks a lot.

LGTM :sparkles:

2019-06-09 09:24 UTC, merged