Updated Readme with installation instructions
oss2019/naarad pull request #27
Opened 2019-07-01 03:48 UTC by iharshit009

2019-07-01 06:21 UTC, thealphadollar requested changes

2019-07-01 06:21 UTC, thealphadollar commented on README.md
> +$ sudo pip install selenium
I don't think these instructions are enough as I got an error that chromedriver could not be found. Can you please look into this?

2019-07-01 06:23 UTC, iharshit009 commented
Sir actually the webdriver .exe file should be inside the folder where our
.py file is present...

Them it would work...

On Mon 1 Jul, 2019, 11:51 Shivam Kumar Jha, <notifications@github.com>
wrote:

> *@thealphadollar* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/oss2019/naarad/pull/27#discussion_r298893467>:
>
> > @@ -64,6 +67,17 @@ Once in the virtual environment, use the command `pipenv install PACKAGE_NAME1 P
>
>  **NOTE:** Do not install packages without pipenv. We will not be supporting requirements.txt standard.
>
> +#### For Windows
> +
> +[Download](https://www.seleniumhq.org/download/) the web driver according to version/type of your browser. Make sure that EXE file downloaded is inside the the project folder. In your development environment you can run the py file.
> +
> +#### For Linux
> +
> +Follow this command in your development Environment in your project folder
> +```
> +$ sudo apt-get install python-pip
> +$ sudo pip install selenium
>
> I don't think these instructions are enough as I got an error that
> chromedriver could not be found. Can you please look into this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AKQXHFAHE3XFY4J3T6UGXFTP5GO7BA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5CH2VQ#pullrequestreview-256146774>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKQXHFB7N4V7S45EY33U77LP5GO7BANCNFSM4H4ONGZA>
> .
>

2019-07-01 06:33 UTC, thealphadollar commented
Please add all instructions, including this, to the readme. One should be
able to blindly follow the instructions and get the application running.

On Mon 1 Jul, 2019, 11:53 HARSHIT JAIN, <notifications@github.com> wrote:

> Sir actually the webdriver .exe file should be inside the folder where our
> .py file is present...
>
> Them it would work...
>
> On Mon 1 Jul, 2019, 11:51 Shivam Kumar Jha, <notifications@github.com>
> wrote:
>
> > *@thealphadollar* requested changes on this pull request.
> > ------------------------------
> >
> > In README.md
> > <https://github.com/oss2019/naarad/pull/27#discussion_r298893467>:
> >
> > > @@ -64,6 +67,17 @@ Once in the virtual environment, use the command
> `pipenv install PACKAGE_NAME1 P
> >
> > **NOTE:** Do not install packages without pipenv. We will not be
> supporting requirements.txt standard.
> >
> > +#### For Windows
> > +
> > +[Download](https://www.seleniumhq.org/download/) the web driver
> according to version/type of your browser. Make sure that EXE file
> downloaded is inside the the project folder. In your development
> environment you can run the py file.
> > +
> > +#### For Linux
> > +
> > +Follow this command in your development Environment in your project
> folder
> > +```
> > +$ sudo apt-get install python-pip
> > +$ sudo pip install selenium
> >
> > I don't think these instructions are enough as I got an error that
> > chromedriver could not be found. Can you please look into this?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AKQXHFAHE3XFY4J3T6UGXFTP5GO7BA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5CH2VQ#pullrequestreview-256146774
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AKQXHFB7N4V7S45EY33U77LP5GO7BANCNFSM4H4ONGZA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AH2K2ICZ3RPVN7BLNTOC7ODP5GPGNA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY5DP5Q#issuecomment-507131894>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AH2K2ICMVWSP5RGSREVPXJTP5GPGNANCNFSM4H4ONGZA>
> .
>

2019-07-01 06:37 UTC, iharshit009 commented
Okay sir

On Mon 1 Jul, 2019, 12:03 Shivam Kumar Jha, <notifications@github.com>
wrote:

> Please add all instructions, including this, to the readme. One should be
> able to blindly follow the instructions and get the application running.
>
> On Mon 1 Jul, 2019, 11:53 HARSHIT JAIN, <notifications@github.com> wrote:
>
> > Sir actually the webdriver .exe file should be inside the folder where
> our
> > .py file is present...
> >
> > Them it would work...
> >
> > On Mon 1 Jul, 2019, 11:51 Shivam Kumar Jha, <notifications@github.com>
> > wrote:
> >
> > > *@thealphadollar* requested changes on this pull request.
> > > ------------------------------
> > >
> > > In README.md
> > > <https://github.com/oss2019/naarad/pull/27#discussion_r298893467>:
> > >
> > > > @@ -64,6 +67,17 @@ Once in the virtual environment, use the command
> > `pipenv install PACKAGE_NAME1 P
> > >
> > > **NOTE:** Do not install packages without pipenv. We will not be
> > supporting requirements.txt standard.
> > >
> > > +#### For Windows
> > > +
> > > +[Download](https://www.seleniumhq.org/download/) the web driver
> > according to version/type of your browser. Make sure that EXE file
> > downloaded is inside the the project folder. In your development
> > environment you can run the py file.
> > > +
> > > +#### For Linux
> > > +
> > > +Follow this command in your development Environment in your project
> > folder
> > > +```
> > > +$ sudo apt-get install python-pip
> > > +$ sudo pip install selenium
> > >
> > > I don't think these instructions are enough as I got an error that
> > > chromedriver could not be found. Can you please look into this?
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AKQXHFAHE3XFY4J3T6UGXFTP5GO7BA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5CH2VQ#pullrequestreview-256146774
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AKQXHFB7N4V7S45EY33U77LP5GO7BANCNFSM4H4ONGZA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AH2K2ICZ3RPVN7BLNTOC7ODP5GPGNA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY5DP5Q#issuecomment-507131894
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AH2K2ICMVWSP5RGSREVPXJTP5GPGNANCNFSM4H4ONGZA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/oss2019/naarad/pull/27?email_source=notifications&email_token=AKQXHFE4O2WLU56PHVRTWOLP5GQNBA5CNFSM4H4ONGZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY5ECXI#issuecomment-507134301>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKQXHFGZOPOPXT6ZJWTHUYLP5GQNBANCNFSM4H4ONGZA>
> .
>

2019-07-08 20:28 UTC, iharshit009 commented
@thealphadollar sir Is it still incomplete or any part not working 
or it needs any updates??

2019-07-09 12:56 UTC, thealphadollar reviewed
Great work.

2019-07-09 12:56 UTC, thealphadollar commented
@iharshit009 I apologize for the late response. The PR looks good to me.

2019-07-09 12:56 UTC, merged